## Preprocessing

In [26]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from keras.layers import Flatten

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
application_df = pd.read_csv("/content/drive/MyDrive/ColabDemo/alphapet_soup/charity_data.csv")

In [4]:
application_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [5]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df= application_df.drop(['EIN', 'NAME'],axis=1)

In [6]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
app_type_value_counts = application_df['APPLICATION_TYPE'].value_counts()
app_type_value_counts[app_type_value_counts<600]

T10    528
T9     156
T13     66
T12     27
T2      16
T25      3
T14      3
T29      2
T15      2
T17      1
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = app_type_value_counts[app_type_value_counts<600].index
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
classbinning = application_df['CLASSIFICATION'].value_counts()

classbinning

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
classify = classbinning[classbinning>1]
classify

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = classbinning[classbinning<100].index
# Replace in dataframe
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] =application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [12]:
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,Other,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE

application_df = pd.get_dummies(application_df,dtype=float)

In [14]:
application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [15]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(columns = "IS_SUCCESSFUL", axis=1).values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [37]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn_model = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn_model.add(tf.keras.layers.Dense(units=14, activation="relu", input_dim=48))

# Second hidden layer
#  YOUR CODE GOES HERE
nn_model.add(tf.keras.layers.Dense(units=8, activation="relu"))
nn_model.add(Flatten())
#Third hidden layer 
#nn_model.add(tf.keras.layers.Dense(units=7, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
# Check the structure of the model
nn_model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_21 (Dense)            (None, 14)                686

 dense_22 (Dense)            (None, 8)                 120

 flatten_3 (Flatten)         (None, 8)                 0

 dense_23 (Dense)            (None, 1)                 9

=================================================================
Total params: 815
Trainable params: 815
Non-trainable params: 0
_________________________________________________________________

In [38]:
# Compile the model
#  YOUR CODE GOES HERE
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [39]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5924 - accuracy: 0.7034
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5579 - accuracy: 0.7252
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5537 - accuracy: 0.7264
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5518 - accuracy: 0.7283
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5507 - accuracy: 0.7294
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7308
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7306
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5481 - accuracy: 0.7313
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5477 - accuracy: 0.7306
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7313
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7311
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7326
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7326
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7318
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7340
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5450 - accuracy: 0.7329
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7332
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7331
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7338
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7325
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7342
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7331
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7338
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7322
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7331
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7332
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7341
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7334
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7339
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7341
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7339
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7346
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5422 - accuracy: 0.7348
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7336
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7348
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7343
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7334
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7344
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7343
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7352
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7348
Epoch 42/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5412 - accuracy: 0.7338
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7345
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7344
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7338
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7355
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7354
Epoch 48/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5406 - accuracy: 0.7356
Epoch 49/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5410 - accuracy: 0.7351
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7352
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7354
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7356
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7347
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7348
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7353
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5400 - accuracy: 0.7358
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5402 - accuracy: 0.7346
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7353
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7349
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7355
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7347
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7362
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7365
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7354
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5396 - accuracy: 0.7357
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7358
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7353
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7349
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7360
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7359
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7358
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7357
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7358
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5389 - accuracy: 0.7365
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7358
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7357
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7363
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7361
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7360
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7363
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7353
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7362
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7354
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7362
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7356
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7358
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7357
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7365
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7360
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5383 - accuracy: 0.7363
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5383 - accuracy: 0.7369
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7358
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5385 - accuracy: 0.7366
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7357
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7355
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7364
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7362
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7364
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7361
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5380 - accuracy: 0.7366

In [40]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5520 - accuracy: 0.7265 - 543ms/epoch - 2ms/step
Loss: 0.5520482659339905, Accuracy: 0.7265306115150452